repos:
  # Ruff: lint & format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # pre-commit-hooks: 基本チェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  # Local hook for pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest quick
        entry: uv run pytest --maxfail=1 --disable-warnings -q
        language: system
        types: [python]
